import clsx from "clsx";
import { BigNumber } from "ethers";

import { BodyText, Display, Icon, Tooltip } from "@/components/design-system";
import { formatCrypto } from "@/lib/format";
import { SupportedCrypto } from "@/lib/graphql/generated";
type Props = {
  totalRevenue: number;
};

const ToolTipInformation = () => (
  <div className="max-w-xs">
    <div className="mb-4 text-xl font-bold text-dark-80">
      Total Pool Revenue
    </div>
    <div>
      Total revenue is the total revenue accrued by the pool based on the
      artists contributions to the pool.
    </div>
  </div>
);

export function BackerRevenueCard({ totalRevenue }: Props) {
  return (
    <div className="mt-2 flex items-center">
      <div className="w-full items-center p-6">
        <BodyText size="normal" className="text-light-40">
          Total Pool Revenue
        </BodyText>
        <BodyText size="small" className="mt-2 text-light-40">
          Revenue generated by artist
        </BodyText>

        <div className="my-4 w-full border border-dark-50" />

        <BodyText size="small" className="mt-2 text-dark-70">
          Total Revenue{" "}
          <Tooltip placement="right" content={<ToolTipInformation />}>
            <button>
              <Icon
                name="InfoCircle"
                size={"sm"}
                className={clsx("text-sand-400")}
              />
            </button>
          </Tooltip>
        </BodyText>

        <Display level={2} className="text-light-40">
          {formatCrypto({
            token: SupportedCrypto.Usdc,
            amount: BigNumber.from(totalRevenue ?? 0),
          })}
        </Display>
      </div>
    </div>
  );
}
